nix: use TMPDIR for cache locations
Hardcoding /tmp is fine for Linux but on macOS hosts due to lackluster
sandboxing weird errors due to corrupted Nim cache can appear.

Error: cannot open '/tmp/nim/koch_d/@psystem@sexceptions.nim.c'

Signed-off-by: Jakub Sokołowski <jakub@status.im>